import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  // 1. On change le nom de la variable ici pour correspondre à shadcn
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono", // Optionnel : utile si vous utilisez des blocs de code
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
          lang="en"
          className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
      {/* 2. On ajoute font-sans, bg-background et text-foreground */}
      <body className="min-h-full flex flex-col font-sans bg-background text-foreground">
      <Navbar />
      {children}
      </body>
      </html>
  );
}